GET http://localhost:3000/api/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54YW1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Imd2ZXJhQHV2Lm14IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiR3VpbGxlcm1vIFZlcmEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiaXNzIjoiU2Vydmlkb3JGZWlKV1QiLCJhdWQiOiJDbGllbnRlc0ZlaUpXVCIsImlhdCI6MTcxNTQ0NDYxNCwiZXhwIjoxNzE1NDQ1ODE0fQ.1EqCKAsW63JOXw5FXPI0XuQ4XmH6KSDVNow5nbOiW6w

###
GET http://localhost:3000/api/peliculas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54YW1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Imd2ZXJhQHV2Lm14IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiR3VpbGxlcm1vIFZlcmEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiaXNzIjoiU2Vydmlkb3JGZWlKV1QiLCJhdWQiOiJDbGllbnRlc0ZlaUpXVCIsImlhdCI6MTcxNTQ0MzczOCwiZXhwIjoxNzE1NDQ0OTM4fQ.GJZKTye9ghKtHpi9zvOO9CTnYF9JZgwQiy3KpL3c174

###
GET http://localhost:3000/api/bitacoras
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54YW1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Imd2ZXJhQHV2Lm14IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiR3VpbGxlcm1vIFZlcmEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiaXNzIjoiU2Vydmlkb3JGZWlKV1QiLCJhdWQiOiJDbGllbnRlc0ZlaUpXVCIsImlhdCI6MTcxNTQ0MzczOCwiZXhwIjoxNzE1NDQ0OTM4fQ.GJZKTye9ghKtHpi9zvOO9CTnYF9JZgwQiy3KpL3c174

###
POST http://localhost:3000/api/categorias
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54YW1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Imd2ZXJhQHV2Lm14IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS9pZGVudGl0eS9jbGFpbXMvZ2l2ZW5uYW1lIjoiR3VpbGxlcm1vIFZlcmEiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhZG9yIiwiaXNzIjoiU2Vydmlkb3JGZWlKV1QiLCJhdWQiOiJDbGllbnRlc0ZlaUpXVCIsImlhdCI6MTcxNTQ0NTEzOSwiZXhwIjoxNzE1NDQ2MzM5fQ.SOqUs0iTpdk-jMCP-AuRvzpE4rKFYSGJ__Nv0B4bTXE

{
    "nombre": "Categoria de prueba"
}

###
 
POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "username": "gvera@uv.mx",
    "password": "patito"
}

